web_server:
  port: 80
  version: 3
  include_internal: true

external_components:
  - source:
      type: git
      url: https://github.com/xiaoxianNo1/esphome-components.git
      ref: dev
    components: [ ra2413mt ]

ra2413mt:

text_sensor:
  - platform: wifi_info
    ip_address:
      name: device_ip
      icon: mdi:ip-outline
      internal: true
    mac_address:
      name: device_mac
      icon: mdi:map-marker-outline
      internal: true
      
binary_sensor:
  - platform: gpio
    # 2413有人输出口
    pin: 4
    id: mmw
    name: mmw
    device_class: occupancy
    icon: mdi:motion-sensor
  - platform: gpio
    pin:
      number: 2
      mode:
        input: true
        pullup: true
      inverted: true
    name: button
    icon: mdi:radiobox-marked
    internal: true
    on_click: 
      then:
        - button.press: reboot
    on_double_click: 
      then:
        - button.press: reset_mmw
    on_multi_click: 
      - timing: 
          - ON for 1s to 5s
          - OFF for at least 0.5s
        then: 
          - button.press: reset_mmw
          - delay: 0.5s
          - button.press: restart_factory_setting

sensor:
  - platform: uptime
    #运行时间
    name: uptime
    
  - platform: wifi_signal
    #信号强度
    name: signal
    update_interval: 60s
    
  - platform: adc
    pin: 3
    name: brightness
    attenuation: 11db
    update_interval: 5s
    unit_of_measurement: "%"
    icon: mdi:brightness-6
    accuracy_decimals: 0
    filters:
      - lambda: |-
          return ( 3 - x ) / 0.03;
    
  - platform: internal_temperature
    #CPU温度
    id: cpu_temprature 
    name: cpu_temprature

  - platform: ra2413mt    
    move_distance:
      name: 'move_distance'

    move_energy:
      name: 'move_energy'

    static_distance:
      name: 'static_distance'

    static_energy:
      name: 'static_energy'

button:
  - platform: restart
    #重启esp模块
    name: reboot
    id: reboot

  - platform: ra2413mt
    get_conf:
      name: 'query_conf'
    reset_conf:
      name: 'reset_mmw'
      id: reset_mmw
  - platform: factory_reset
    name: restart_factory_setting
    id: restart_factory_setting

number:
  - platform: ra2413mt
    max_move_distance:
      name: 'max_move_distance'
      unit_of_measurement: x 0.75m

    max_static_distance:
      name: 'max_static_distance'
      unit_of_measurement: x 0.75m

    move_sensitivity:
      name: 'move_sensitivity'

    static_sensitivity:
      name: 'static_sensitivity'

    unattended_duration:
      name: 'unattended_duration'
